### ISSUE TITLE
Connecting CodecNode to ScaleNode crashes Gogh

### ISSUE THREAD

**Issue by Tilix4** [eliemichel/CodenameGogh#21]
When I try to link the CodecNode to the ScaleNode, Gogh crashes instantly. It crashes even if I make the link the opposite way.

**Comment by eliemichel** [comment]
I cannot reproduce this. Is it still crashing for you?
![gogh13](https://user-images.githubusercontent.com/5802849/43761743-3c0fd250-9a26-11e8-8416-dfb9c0d5e207.png)

**Comment by Tilix4** [comment]
I found it's related to issue #12, it crashed because they were away from each other and I was taking too much time to link them.
