### ISSUE TITLE
Reactive Node display when linked

### ISSUE THREAD

**Issue by Tilix4** [eliemichel/CodenameGogh#22]
This is the base to have smart behaviour depending on what the node has in input.
For example the **CodeNode** is empty if not linked. It displays video codecs if the input is a video stream and audio codecs if the input is an audio stream.

**Comment by eliemichel** [comment]
This should be implemented through a virtual protected `slotConnectEvent(int slot)` in the `NodeWidget` class and called by the slot connection mechanism. Hence any custom behavior needed when a slot is connected will be implemented in an override of this method in subclasses of `NodeWidget`.

This is the same mechanism as the one used for mouse/keyboard/etc. event handling in Qt.

**Comment by Tilix4** [comment]
The event trigger is good, but the node widget doesn't update if in this event I choose to add a new input. It doesn't change at all.
```
void MixNode::slotConnectEvent(SlotEvent *event)
{
	if (event->isInputSlot() && event->slotIndex() == 0)
	{
		newInputSlot();
	}
}
```

**Comment by eliemichel** [comment]
This is an unrelated issue. I opened a new bug report: #27
