### ISSUE TITLE
Create MixNode

### ISSUE THREAD

**Issue by Tilix4** [eliemichel/CodenameGogh#6]
The MixNode takes many input streams and mixes them into a single stream to go to the OutputNode.

**Comment by eliemichel** [comment]
Could you add a mockup for new node suggestions? A picture or an ascii-art.

**Comment by Tilix4** [comment]
Of course, when I'll have time to do it.

**Comment by Tilix4** [comment]
Waiting for the #22 fix.

**Comment by eliemichel** [comment]
Which is actually #27

**Comment by Tilix4** [comment]
- [x] Stream Mapping
- [ ] Stream keep filters (codec, scale, etc...)
